version: "3"
services:
  mariadb:
    # Sakai requires the database to use UTF-8.
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      # See https://docs.docker.com/samples/library/mysql/#environment-variables
      MYSQL_DATABASE: sakai
      MYSQL_USER: sakai
      MYSQL_PASSWORD: sakaipass
      MYSQL_ROOT_PASSWORD: rootpass
    image: mariadb:10.9
  sakai:
    build: .
    depends_on:
      - mariadb
    environment:
      DATABASE_HOST: mariadb:3306
      DATABASE_NAME: sakai
      DATABASE_USER: sakai
      DATABASE_PASSWORD: sakaipass
    image: cas/sakai:latest
    ports:
            - "8080:8080"
